### ISSUE TITLE
TypeError: data.filter is not a function

### ISSUE THREAD

**Issue by ameem91** [TestArmada/guacamole#40]
Hi,

I am seeing intermittent errors when running browser identification. Example command:

`npx guacamole --id=chrome_latest_Windows_10_Desktop` , which will sometimes result in:

```
error: TypeError: data.filter is not a function
    at Object._normalize (/Users/Ashaik/workspace/sci.ref/discover.academic.basic-ui/node_modules/guacamole/src/browsers.js:221:8)
    at SauceBrowsers._fetch.then (/Users/Ashaik/workspace/sci.ref/discover.academic.basic-ui/node_modules/guacamole/src/browsers.js:487:34)
    at _fulfilled (/Users/Ashaik/workspace/sci.ref/discover.academic.basic-ui/node_modules/guacamole/node_modules/q/q.js:854:54)
    at /Users/Ashaik/workspace/sci.ref/discover.academic.basic-ui/node_modules/guacamole/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/Users/Ashaik/workspace/sci.ref/discover.academic.basic-ui/node_modules/guacamole/node_modules/q/q.js:816:13)
    at /Users/Ashaik/workspace/sci.ref/discover.academic.basic-ui/node_modules/guacamole/node_modules/q/q.js:624:44
    at runSingle (/Users/Ashaik/workspace/sci.ref/discover.academic.basic-ui/node_modules/guacamole/node_modules/q/q.js:137:13)
    at flush (/Users/Ashaik/workspace/sci.ref/discover.academic.basic-ui/node_modules/guacamole/node_modules/q/q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)
TypeError: data.filter is not a function
    at Object._normalize (/Users/Ashaik/workspace/sci.ref/discover.academic.basic-ui/node_modules/guacamole/src/browsers.js:221:8)
    at SauceBrowsers._fetch.then (/Users/Ashaik/workspace/sci.ref/discover.academic.basic-ui/node_modules/guacamole/src/browsers.js:487:34)
    at _fulfilled (/Users/Ashaik/workspace/sci.ref/discover.academic.basic-ui/node_modules/guacamole/node_modules/q/q.js:854:54)
    at /Users/Ashaik/workspace/sci.ref/discover.academic.basic-ui/node_modules/guacamole/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/Users/Ashaik/workspace/sci.ref/discover.academic.basic-ui/node_modules/guacamole/node_modules/q/q.js:816:13)
    at /Users/Ashaik/workspace/sci.ref/discover.academic.basic-ui/node_modules/guacamole/node_modules/q/q.js:624:44
    at runSingle (/Users/Ashaik/workspace/sci.ref/discover.academic.basic-ui/node_modules/guacamole/node_modules/q/q.js:137:13)
    at flush (/Users/Ashaik/workspace/sci.ref/discover.academic.basic-ui/node_modules/guacamole/node_modules/q/q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)
``` 

Again, want to emphasize that that the error is intermittent, you may have to run it a few times before being able to reproduce it.

**Comment by esimons** [comment]
Looks like Guacamole always makes unauthenticated requests, which might be triggering rate-limiting. 

Given that most consumers are probably invoking this plugin via the [SauceLabs executor](TestArmada/magellan-saucelabs-executor), and that the environment variables `SAUCE_USERNAME` and `SAUCE_ACCESS_KEY` should be available in that context, it should be pretty straightforward to make calls using basic auth in the presence of those env variables and fall back to unauthenticated calls otherwise, right?

**Comment by archlichking** [comment]
The request guacamole uses to pull saucelabs capabilities uses public saucelabs api https://saucelabs.com/rest/v1/info/platforms/all?resolutions=true. According to saucelabs, `Not authenticated requests are allowed up to 2 requests per minute rate. `.

**Comment by esimons** [comment]
Hi @archlichking,
#41 should resolve this, and was merged, but we need Guacamole to be published with those changes.

**Comment by archlichking** [comment]
@esimons thanks for the PR. `guacamole@3.2.3` is out with your change.
